"""
backend/soc/soc_audit.py — SOC Event Audit Logger

Records full SOC lifecycle events into the soc_audit_log SQLite table.
This is a separate, simpler log from the tamper-evident SHA-256 hash-chained
audit_log used for code-based rule deployment.

Supported event types:
  TRANSACTION_CREATED   — New transaction generated by simulator
  SCORE_COMPUTED        — Risk score computed by scoring engine
  ALERT_CREATED         — Transaction flagged as HIGH_RISK / SUSPICIOUS
  RULE_DEPLOYED         — New SOC prevention rule deployed
  RULE_MATCHED          — A deployed rule was matched against a transaction
  CHALLENGE_TRIGGERED   — Transaction challenged (OTP/CAPTCHA required)
  TRANSACTION_BLOCKED   — Transaction blocked by a SOC rule
  TRANSACTION_ALLOWED   — Transaction passed all rules and allowed
"""

from datetime import datetime, timezone
from typing import List, Dict, Any

from backend.core.db import get_db_connection, init_db, DEFAULT_DB_PATH


def log_soc_event(
    event_type: str,
    transaction_id: str,
    action: str,
    risk_score: float = 0.0,
    rule_id: str = "",
    reason: str = "",
    db_path: str = DEFAULT_DB_PATH,
) -> Dict[str, Any]:
    """Insert a single SOC audit event. Returns the created log entry dict."""
    init_db(db_path)
    conn = get_db_connection(db_path)
    cursor = conn.cursor()
    try:
        timestamp = datetime.now(timezone.utc).isoformat()
        cursor.execute(
            """
            INSERT INTO soc_audit_log (timestamp, transaction_id, rule_id, event_type, action, risk_score, reason)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (timestamp, transaction_id, rule_id, event_type, action, risk_score, reason),
        )
        conn.commit()
        entry_id = cursor.lastrowid
        return {
            "id": entry_id,
            "timestamp": timestamp,
            "transaction_id": transaction_id,
            "rule_id": rule_id,
            "event_type": event_type,
            "action": action,
            "risk_score": risk_score,
            "reason": reason,
        }
    finally:
        conn.close()


def get_soc_audit_logs(limit: int = 200, db_path: str = DEFAULT_DB_PATH) -> List[Dict[str, Any]]:
    """Fetch recent SOC audit log entries (newest first)."""
    init_db(db_path)
    conn = get_db_connection(db_path)
    cursor = conn.cursor()
    try:
        cursor.execute(
            "SELECT * FROM soc_audit_log ORDER BY id DESC LIMIT ?", (limit,)
        )
        rows = cursor.fetchall()
        return [
            {
                "id": r["id"],
                "timestamp": r["timestamp"],
                "transaction_id": r["transaction_id"],
                "rule_id": r["rule_id"],
                "event_type": r["event_type"],
                "action": r["action"],
                "risk_score": r["risk_score"],
                "reason": r["reason"],
            }
            for r in rows
        ]
    finally:
        conn.close()
