"""
Data Contracts for Fraud Detection Rules Engine.

# CONTRACT: Confirm with Person B - Field names and types are shared contracts
between Person A's backend engine and Person B's frontend/orchestrator.
"""

from datetime import datetime
from typing import Optional, Any, Dict, List
from pydantic import BaseModel, Field, ConfigDict


class Transaction(BaseModel):
    """
    Core Transaction object generated by simulator and evaluated by rules engine.
    """
    id: str = Field(..., description="Unique transaction ID e.g. tx_102030")
    account_id: str = Field(..., description="Account identifier e.g. acc_9910")
    amount: float = Field(..., description="Transaction amount in USD")
    location: str = Field(..., description="Location code or country code e.g. US-NY, RU-MOS")
    timestamp: str = Field(..., description="ISO 8601 timestamp of transaction")
    account_age_days: int = Field(..., description="Age of account in days")
    merchant_category: str = Field(..., description="Category e.g. electronics, crypto, retail, travel")
    device_id: str = Field(..., description="Device fingerprint ID")
    is_international: bool = Field(default=False, description="Flag indicating cross-border transaction")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "tx_88301",
                "account_id": "acc_4412",
                "amount": 2450.00,
                "location": "RU-MOS",
                "timestamp": "2026-07-27T12:00:00Z",
                "account_age_days": 5,
                "merchant_category": "crypto",
                "device_id": "dev_3391",
                "is_international": True
            }
        }
    )


class FlaggedAlert(BaseModel):
    """
    Alert emitted when a transaction triggers an active fraud rule.
    Emitted immediately via WebSocket to Person B's UI.
    """
    id: str = Field(..., description="Unique alert ID e.g. alt_7721")
    transaction_id: str = Field(..., description="ID of the triggering transaction")
    rule_id: str = Field(..., description="ID of the rule that triggered")
    rule_name: str = Field(..., description="Human-readable rule name")
    score: float = Field(default=1.0, description="Risk score assigned by rule (0.0 - 1.0)")
    flagged_at: str = Field(..., description="ISO 8601 timestamp when alert was generated")
    transaction_details: Transaction = Field(..., description="Full transaction payload for analyst context")


class Rule(BaseModel):
    """
    Fraud detection rule stored in database and active rules engine.
    """
    id: str = Field(..., description="Unique rule ID e.g. rule_001")
    name: str = Field(..., description="Short descriptive rule title")
    code: str = Field(..., description="Python source code containing evaluate(tx) function")
    description: str = Field(..., description="Detailed description of detection logic")
    created_at: str = Field(..., description="ISO timestamp when rule was created")
    status: str = Field(default="active", description="Status: 'active' or 'reverted'")
    created_by_command: str = Field(..., description="Original analyst command or prompt that created this rule")


class CustomProfile(BaseModel):
    """
    Configuration for simulator bias injection (Person B's Custom Profile Builder calls this).
    """
    name: str = Field(default="custom", description="Profile name")
    amount_min: Optional[float] = Field(default=None, description="Minimum transaction amount bias")
    amount_max: Optional[float] = Field(default=None, description="Maximum transaction amount bias")
    high_risk_location_bias: float = Field(default=0.0, description="Probability (0.0-1.0) of generating high-risk location")
    new_account_bias: float = Field(default=0.0, description="Probability (0.0-1.0) of account age < 14 days")
    merchant_category_filter: Optional[List[str]] = Field(default=None, description="Target specific merchant categories")


class ValidationResult(BaseModel):
    """
    Result returned by AST Safety Validator (core/validator.py).
    Read by Person B's rule-writer agent on error for retries.
    """
    valid: bool = Field(..., description="True if code passes all static AST checks and sandboxed dry-run")
    error: Optional[str] = Field(default=None, description="Detailed actionable error string if invalid")
    line_number: Optional[int] = Field(default=None, description="Line number of violation if applicable")


class GuardResult(BaseModel):
    """
    Result returned by Rule Guard (core/rule_guard.py).
    Checks rule size cap (max 20 rules) and semantic duplicate threshold.
    """
    passed: bool = Field(..., description="True if rule can be deployed")
    reason: Optional[str] = Field(default=None, description="Rejection reason if passed=False")
    similarity_score: Optional[float] = Field(default=None, description="Highest cosine similarity score found")
    duplicate_rule_id: Optional[str] = Field(default=None, description="ID of existing rule if duplicate detected")


class AuditLogEntry(BaseModel):
    """
    Tamper-evident audit log record for SQLite (core/audit_log.py).
    """
    id: Optional[int] = Field(default=None, description="SQLite autoincrement ID")
    rule_id: str = Field(..., description="ID of rule affected")
    timestamp: str = Field(..., description="ISO timestamp of action")
    command: str = Field(..., description="Action command e.g. DEPLOY_RULE, REVERT_RULE")
    code: str = Field(..., description="Python source code of rule at time of action")
    status: str = Field(..., description="Rule status after action e.g. ACTIVE, REVERTED")
    prev_hash: str = Field(..., description="SHA-256 hash of previous audit log record")
    hash: str = Field(..., description="SHA-256 hash of current audit log record")
